### ISSUE TITLE
Command-line tool / WebAPI for submitting queries?

### ISSUE THREAD

**Issue by d33tah** [AlexTatiyants/pev#10]
It would be nice to run something like this:

```
psql -A -t -X -p 5444 shodan -f - | curl -Ffile=@- http://tatiyants.com/pev/submit
```

And then enter a query and press ctrl+D. Right now copy-pasting JSON code over an SSH server to the website can be a bit troublesome.

**Comment by AlexTatiyants** [comment]
Pev doesn't really have a server component, it's a brower-based app. So this is currently not possible
