### ISSUE TITLE
Information about the privacy?

### ISSUE THREAD

**Issue by d33tah** [AlexTatiyants/pev#11]
Before sending a plan, I couldn't see anywhere the information about what to expect from pev in terms of privacy. Could there be a note about whether it's safe to put private table names there or whether they'd be put on some "recent posts" page, indexable by Google?

**Comment by AlexTatiyants** [comment]
There is a paragraph in the "About" page regarding this. Pev uses browser's localStorage so your queries will not get sent anywhere.

**Comment by d33tah** [comment]
@AlexTatiyants: I see, thanks. Could you add a simple note in the "new plan" view?
