### ISSUE TITLE
navigating a large query is hard, especially side scrolling

### ISSUE THREAD

**Issue by wholtz** [AlexTatiyants/pev#14]
I have a large query that creates a output several monitor widths wide and a couple monitor heights tall. The browser vertical scroll bar works for moving up and down. However, the brower's side-to-side scroll bar doesn't work because pev adds another horizontal scroll bar within the page. This means that I can only scroll side to side when I have navigated to the bottom of the page and made pev's scroll bar visible. This would be much easier if pev's scroll bar was removed. Additionally, it would be useful to be able to zoom in or out on a large tree. Thanks!

**Comment by vsg** [comment]
+1!

**Comment by AlexTatiyants** [comment]
agreed. Once I find a bit of time, I'll try to find a solution. Also, if you have an example of a plan like that, it would really help.

**Comment by vsg** [comment]
EXPLAIN (ANALYZE, COSTS, VERBOSE, BUFFERS, FORMAT JSON)
select 
(select count(*) from INFORMATION_SCHEMA.tables), 
(select count(*) from INFORMATION_SCHEMA.tables), 
(select count(*) from INFORMATION_SCHEMA.tables), 
(select count(*) from INFORMATION_SCHEMA.tables), 
(select count(*) from INFORMATION_SCHEMA.tables), 
(select count(*) from INFORMATION_SCHEMA.tables)
from INFORMATION_SCHEMA.tables

**Comment by AlexTatiyants** [comment]
I added a "Dot" view mode in commit https://github.com/AlexTatiyants/pev/commit/7fc812bc761c95e508e1c540393b12b03cdf1d03 which should address this.
