### ISSUE TITLE
Site is not served with a valid HTTPS certificate

### ISSUE THREAD

**Issue by miketheman** [AlexTatiyants/pev#37]
With the proliferation of HTTPS and TLS/SSL everywhere, users may find it slightly concerning that the website is not served over a secure protocol.

Despite having the page tell them that no data is transmitted over the wire, it can still make people uneasy when using the site.

**Comment by mgedmin** [comment]
Current versions of Chrome display a scary "Not secure" warning in the address bar.

![ekrano nuotrauka is 2018-11-09 17-01-16](https://user-images.githubusercontent.com/159967/48269791-191ae400-e441-11e8-9212-61cc5cbc388c.png)

[LetsEncrypt](https://letsencrypt.org) is a nice way of getting TLS certificates and could maybe be helpful here?
