### ISSUE TITLE
Feature Idea: Timeline / Gantt Chart as alternative view

### ISSUE THREAD

**Issue by MahatmaFatalError** [AlexTatiyants/pev#47]
Cudos to the author, awesome tool! 

Are there plans or is it even possible with the available information of the query plan to plot more like a timeline instead of a graph? (similar to aws redshift https://docs.aws.amazon.com/redshift/latest/mgmt/analyzing-query-execution.html)

**Comment by pgiraud** [comment]
@MahatmaFatalError FYI, I integrated such a feature in https://github.com/dalibo/pev2
Feedback welcome

**Comment by MahatmaFatalError** [comment]
@pgiraud awesome! I wasn't aware of that new project.
